// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIvfysSseSWfi0uyLhbOJWsGhpNQNWrE',
    appId: '1:1082079894765:web:b9400e9d9d5563fd1940e4',
    messagingSenderId: '1082079894765',
    projectId: 'aht-shop',
    authDomain: 'aht-shop.firebaseapp.com',
    storageBucket: 'aht-shop.firebasestorage.app',
    measurementId: 'G-BVXJEJKT54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7JlR9LQM4tvcp-0C4HD4pn-M0t7Jnrk',
    appId: '1:1082079894765:android:4f1304de6541f9231940e4',
    messagingSenderId: '1082079894765',
    projectId: 'aht-shop',
    storageBucket: 'aht-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaxIWytT9pPXjbUJctWSy7c_Z2qNK0BQE',
    appId: '1:1082079894765:ios:ad111e0a54623c771940e4',
    messagingSenderId: '1082079894765',
    projectId: 'aht-shop',
    storageBucket: 'aht-shop.firebasestorage.app',
    iosBundleId: 'com.example.ahtshopdongho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaxIWytT9pPXjbUJctWSy7c_Z2qNK0BQE',
    appId: '1:1082079894765:ios:ad111e0a54623c771940e4',
    messagingSenderId: '1082079894765',
    projectId: 'aht-shop',
    storageBucket: 'aht-shop.firebasestorage.app',
    iosBundleId: 'com.example.ahtshopdongho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeIvfysSseSWfi0uyLhbOJWsGhpNQNWrE',
    appId: '1:1082079894765:web:2ad1a11bf73fa93c1940e4',
    messagingSenderId: '1082079894765',
    projectId: 'aht-shop',
    authDomain: 'aht-shop.firebaseapp.com',
    storageBucket: 'aht-shop.firebasestorage.app',
    measurementId: 'G-YTPGYY9CSG',
  );
}
